/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sri Dayanti
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import calmirea.panelgradasi;

public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
       // ICON BUKU
       ImageIcon icon = new ImageIcon(getClass().getResource("/images/Book.png"));
       
       java.awt.Image img = icon.getImage().getScaledInstance( 
               60, 60, java.awt.Image.SCALE_SMOOTH);
       
       aplikasiperpustakaanLB.setIcon(new ImageIcon(img));
       
       // POSISI TEXT
       aplikasiperpustakaanLB.setHorizontalTextPosition( javax.swing.SwingConstants.RIGHT);
       aplikasiperpustakaanLB.setIconTextGap(15);
       
        // GESER KE KANAN
        aplikasiperpustakaanLB.setBorder(
        javax.swing.BorderFactory.createEmptyBorder(
            0, 10, 0, 0
        )
    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new calmirea.panelgradasi();
        aplikasiperpustakaanLB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        loginBT = new javax.swing.JButton();
        passwordPF = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aplikasiperpustakaanLB.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        aplikasiperpustakaanLB.setText("APLIKASI PERPUSTAKAAN");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        usernameTF.addActionListener(this::usernameTFActionPerformed);

        loginBT.setBackground(new java.awt.Color(255, 102, 102));
        loginBT.setText("Login");
        loginBT.addActionListener(this::loginBTActionPerformed);

        passwordPF.addActionListener(this::passwordPFActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(usernameTF, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(aplikasiperpustakaanLB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(loginBT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(aplikasiperpustakaanLB)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(loginBT)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        passwordPF.requestFocus();
    }//GEN-LAST:event_usernameTFActionPerformed

    private void loginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTActionPerformed

    String username = usernameTF.getText();
    String password = String.valueOf(passwordPF.getPassword());

    try {

        Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/perpustakaan",
                "root",
                ""
        );

        // cek username dulu
        String sql = "SELECT * FROM users WHERE username=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            // ambil password dari database
            String pwDatabase = rs.getString("password");

            // cek password
            if (password.equals(pwDatabase)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Login Berhasil! Selamat datang, " + username
                );

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Password Salah"
                );
            }

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Username Salah"
            );
        }

        conn.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Koneksi Gagal : " + e.getMessage()
        );
    }
    }//GEN-LAST:event_loginBTActionPerformed

    private void passwordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try { 
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) { 
                
                if ("Nimbus".equals(info.getName())) { 
                    
                    javax.swing.UIManager.setLookAndFeel( info.getClassName()); 
                    
                    break; 
                } 
            } 
        } catch (ReflectiveOperationException 
            | javax.swing.UnsupportedLookAndFeelException ex) {
            
            logger.log( java.util.logging.Level.SEVERE, 
                    null, ex); 
        } 
        
        java.awt.EventQueue.invokeLater( () -> { 
            new Login().setVisible(true); 
        });
    }

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aplikasiperpustakaanLB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginBT;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
