/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sri Dayanti
 */

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.ImageIcon;
import java.awt.Image;
import calmirea.panelgradasi;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Peminjaman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Peminjaman.class.getName());

    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
    initComponents();
    
     // paksa reset combobox
    peminjamCMB.setModel(
        new javax.swing.DefaultComboBoxModel<>()
    );
    
    tampilTanggal();
    isiComboPeminjam();
    isiComboBuku();
    loadTabel();

     tampilGambar();
     tengahKolomNo(); 
}
  
    
   private void tengahKolomNo() {

    // isi data kolom No ke tengah
    DefaultTableCellRenderer center =
            new DefaultTableCellRenderer();

    center.setHorizontalAlignment(
            javax.swing.SwingConstants.CENTER
    );

    peminjamanTB.getColumnModel()
            .getColumn(0)
            .setCellRenderer(center);

    // header "No" ke tengah
    ((javax.swing.table.DefaultTableCellRenderer)
            peminjamanTB.getTableHeader()
            .getDefaultRenderer())
            .setHorizontalAlignment(
                    javax.swing.JLabel.CENTER
            );
}
    
    private void tampilGambar() {

    java.net.URL url =
            getClass().getResource("/images/BukuPeminjaman.png");

    if (url == null) {
        System.out.println("Gambar tidak ditemukan!");
        return;
    }

    ImageIcon icon = new ImageIcon(url);

    Image img = icon.getImage().getScaledInstance(
            180,
            180,
            Image.SCALE_SMOOTH
    );

    jLabel1.setIcon(new ImageIcon(img));
}
    
    private void isiComboPeminjam() {

    peminjamCMB.removeAllItems();

     peminjamCMB.addItem("U001");
    peminjamCMB.addItem("U002");
    peminjamCMB.addItem("U003");
    peminjamCMB.addItem("U004");
    // pilih default
    peminjamCMB.setSelectedIndex(0);
}
    
    private void isiComboBuku() {

    idbukuCMB.removeAllItems();

    idbukuCMB.addItem("F01");
    idbukuCMB.addItem("F02");
    idbukuCMB.addItem("NF01");
     idbukuCMB.addItem("NF02");
     
     idbukuCMB.setSelectedIndex(0);
}
   
    private void loadTabel() {

    DefaultTableModel model =
            (DefaultTableModel) peminjamanTB.getModel();

    model.setRowCount(0);

   model.addRow(new Object[]{
    1,
    "PJM001",
    "U001",
    "Ahmad Fajar",
    "F01",
    "Laskar Pelangi",
    "02/06/2026",
    "09/06/2026",
    "Dipinjam"
});

model.addRow(new Object[]{
    2,
    "PJM002",
    "U002",
    "Siti Aisyah",
    "F02",
    "Bumi",
    "03/06/2026",
    "10/06/2026",
    "Dipinjam"
});

model.addRow(new Object[]{
    3,
    "PJM003",
    "U003",
    "Dewi Lestari",
    "NF01",
    "Matematika",
    "04/06/2026",
    "11/06/2026",
    "Dipinjam"
});

model.addRow(new Object[]{
    4,
    "PJM004",
    "U004",
    "Dedi Saputra",
    "NF02",
    "Fisika",
    "05/06/2026",
    "12/06/2026",
    "Dipinjam"
});

    totaldataTF.setText(
            String.valueOf(model.getRowCount())
    );
} 

    private void tampilTanggal() {
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    tanggalTF.setText(sdf.format(new Date()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new panelgradasi();
        judulLB = new javax.swing.JLabel();
        perpustakaanLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datapeminjamLB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namapeminjamTF = new javax.swing.JTextField();
        peminjamCMB = new javax.swing.JComboBox<>();
        nomorteleponTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        judulbukuTF = new javax.swing.JTextField();
        penulisTF = new javax.swing.JTextField();
        kategoriTF = new javax.swing.JTextField();
        stokTF = new javax.swing.JTextField();
        idbukuCMB = new javax.swing.JComboBox<>();
        cariBT = new javax.swing.JButton();
        datapeminajamanLB = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        idpeminjamanTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tglpinjamTF = new javax.swing.JTextField();
        keteranganTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tglkembaliTF = new javax.swing.JTextField();
        simpanBT = new javax.swing.JButton();
        resetBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();
        cetakBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        peminjamanTB = new javax.swing.JTable();
        kembaliBT = new javax.swing.JButton();
        tanggalTF = new javax.swing.JTextField();
        totaldataLB = new javax.swing.JLabel();
        totaldataTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        petugasTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulLB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        judulLB.setText("PEMINJAMAN BUKU - USER");

        perpustakaanLB.setText("Perpustakaan");

        jLabel3.setText("Tanggal  :");

        datapeminjamLB.setText("DATA PEMINJAM");

        jLabel5.setText("ID Peminjam          :");

        jLabel6.setText("Nama Pemiinjam   :");

        jLabel7.setText("No. Telepon           :");

        jLabel8.setText("Alamat                   :");

        namapeminjamTF.addActionListener(this::namapeminjamTFActionPerformed);

        peminjamCMB.addActionListener(this::peminjamCMBActionPerformed);

        nomorteleponTF.addActionListener(this::nomorteleponTFActionPerformed);

        alamatTF.addActionListener(this::alamatTFActionPerformed);

        Cari.setBackground(new java.awt.Color(255, 102, 102));
        Cari.setText("Cari");
        Cari.addActionListener(this::CariActionPerformed);

        jLabel9.setText("DATA BUKU");

        jLabel10.setText("ID Buku          :");

        jLabel11.setText("Judul Buku     :");

        jLabel12.setText("Penulis           :");

        jLabel13.setText("Kategori        :   ");

        jLabel14.setText("Stok               :");

        judulbukuTF.addActionListener(this::judulbukuTFActionPerformed);

        penulisTF.addActionListener(this::penulisTFActionPerformed);

        kategoriTF.addActionListener(this::kategoriTFActionPerformed);

        stokTF.addActionListener(this::stokTFActionPerformed);

        idbukuCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idbukuCMB.addActionListener(this::idbukuCMBActionPerformed);

        cariBT.setBackground(new java.awt.Color(255, 102, 102));
        cariBT.setText("Cari");
        cariBT.addActionListener(this::cariBTActionPerformed);

        datapeminajamanLB.setText("DATA PEMINJAMAN");

        jLabel16.setText("ID Peminjaman      :");

        jLabel17.setText("Petugas                  :");

        idpeminjamanTF.addActionListener(this::idpeminjamanTFActionPerformed);

        jLabel18.setText("Tanggal Pinjam    :");

        jLabel19.setText("Keterangan           :");

        tglpinjamTF.addActionListener(this::tglpinjamTFActionPerformed);

        keteranganTF.addActionListener(this::keteranganTFActionPerformed);

        jLabel20.setText("Tanggal Kembali     :");

        tglkembaliTF.addActionListener(this::tglkembaliTFActionPerformed);

        simpanBT.setBackground(new java.awt.Color(255, 102, 102));
        simpanBT.setText("Simpan");
        simpanBT.addActionListener(this::simpanBTActionPerformed);

        resetBT.setBackground(new java.awt.Color(255, 102, 102));
        resetBT.setText("Reset");
        resetBT.addActionListener(this::resetBTActionPerformed);

        editBT.setBackground(new java.awt.Color(255, 102, 102));
        editBT.setText("Edit");
        editBT.addActionListener(this::editBTActionPerformed);

        hapusBT.setBackground(new java.awt.Color(255, 102, 102));
        hapusBT.setText("Hapus");
        hapusBT.addActionListener(this::hapusBTActionPerformed);

        cetakBT.setBackground(new java.awt.Color(255, 102, 102));
        cetakBT.setText("Cetak");
        cetakBT.addActionListener(this::cetakBTActionPerformed);

        peminjamanTB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        peminjamanTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Peminjaman", "ID Peminjam", "Nama Peminjam", "ID Buku", "Judul Buku", "Tgl Pinjam", "Tgl Kembali", "Status"
            }
        ));
        jScrollPane1.setViewportView(peminjamanTB);

        kembaliBT.setText("Kembali");
        kembaliBT.addActionListener(this::kembaliBTActionPerformed);

        tanggalTF.setBackground(new java.awt.Color(255, 102, 102));
        tanggalTF.addActionListener(this::tanggalTFActionPerformed);

        totaldataLB.setText("Total Data :");

        totaldataTF.addActionListener(this::totaldataTFActionPerformed);

        petugasTF.addActionListener(this::petugasTFActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datapeminjamLB)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(namapeminjamTF)
                                            .addComponent(alamatTF)
                                            .addComponent(nomorteleponTF)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(peminjamCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                                .addComponent(Cari)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13))
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(kategoriTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(penulisTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(judulbukuTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(idbukuCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cariBT))
                                            .addComponent(stokTF))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(datapeminajamanLB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(simpanBT)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idpeminjamanTF, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(petugasTF))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tglpinjamTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tglkembaliTF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(keteranganTF))
                                .addGap(124, 124, 124))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(resetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(editBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(hapusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cetakBT)
                                .addGap(91, 91, 91))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(judulLB, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(perpustakaanLB)
                        .addGap(76, 76, 76)))
                .addGap(202, 202, 202)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(kembaliBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totaldataLB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totaldataTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(judulLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perpustakaanLB)
                    .addComponent(jLabel3)
                    .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datapeminjamLB)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(peminjamCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cari)
                            .addComponent(jLabel10)
                            .addComponent(idbukuCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariBT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(namapeminjamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(judulbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nomorteleponTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(penulisTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kategoriTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(stokTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(datapeminajamanLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(idpeminjamanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglpinjamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(tglkembaliTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(keteranganTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petugasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpanBT)
                            .addComponent(resetBT)
                            .addComponent(editBT)
                            .addComponent(hapusBT)
                            .addComponent(cetakBT)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaldataLB)
                    .addComponent(totaldataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembaliBT))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglkembaliTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglkembaliTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkembaliTFActionPerformed

    private void kembaliBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBTActionPerformed
         kembaliBT.setBackground(new java.awt.Color(108,117,125));
    kembaliBT.setForeground(java.awt.Color.WHITE);

    this.dispose();
    }//GEN-LAST:event_kembaliBTActionPerformed

    private void tanggalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalTFActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
 String id =
            peminjamCMB.getSelectedItem().toString();

    if(id.equals("U001")){
        namapeminjamTF.setText("Ahmad Fajar");
        nomorteleponTF.setText("081234567890");
        alamatTF.setText("Karawang");

    }else if(id.equals("U002")){
        namapeminjamTF.setText("Siti Aisyah");
        nomorteleponTF.setText("082233445566");
        alamatTF.setText("Bandung");

    }else if(id.equals("U003")){
        namapeminjamTF.setText("Dewi Lestari");
        nomorteleponTF.setText("083344556677");
        alamatTF.setText("Jakarta");

    }else if(id.equals("U004")){
        namapeminjamTF.setText("Dedi Saputra");
        nomorteleponTF.setText("084455667788");
        alamatTF.setText("Bekasi");
    }
    }//GEN-LAST:event_CariActionPerformed

    private void namapeminjamTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapeminjamTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapeminjamTFActionPerformed

    private void alamatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatTFActionPerformed

    private void penulisTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penulisTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penulisTFActionPerformed

    private void kategoriTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriTFActionPerformed

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
       
    DefaultTableModel model =
            (DefaultTableModel) peminjamanTB.getModel();

    model.addRow(new Object[]{
        model.getRowCount() + 1,
        idpeminjamanTF.getText(),
        peminjamCMB.getSelectedItem().toString(),
        namapeminjamTF.getText(),
        idbukuCMB.getSelectedItem().toString(),
        judulbukuTF.getText(),
        tglpinjamTF.getText(),
        tglkembaliTF.getText(),
        "Dipinjam"
    });

    totaldataTF.setText(
        String.valueOf(model.getRowCount())
    );
    }//GEN-LAST:event_simpanBTActionPerformed

    private void cetakBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBTActionPerformed
        try{
        peminjamanTB.print();
    }catch(Exception e){
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_cetakBTActionPerformed

    private void peminjamCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjamCMBActionPerformed

    private void nomorteleponTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorteleponTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorteleponTFActionPerformed

    private void idbukuCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbukuCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbukuCMBActionPerformed

    private void cariBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBTActionPerformed
        String id = idbukuCMB.getSelectedItem().toString();

    if(id.equals("F01")){
        judulbukuTF.setText("Laskar Pelangi");
        penulisTF.setText("Andrea Hirata");
        kategoriTF.setText("Fiksi");
        stokTF.setText("5");
    }else if(id.equals("F02")){
        judulbukuTF.setText("Bumi");
        penulisTF.setText("Tere Liye");
        kategoriTF.setText("Novel");
        stokTF.setText("3");
    }else if(id.equals("NF01")){
        judulbukuTF.setText("Pemrograman Java");
        penulisTF.setText("Deitel");
        kategoriTF.setText("Komputer");
        stokTF.setText("7");
    }else if(id.equals("NF02")){
        judulbukuTF.setText("Fisika");
        penulisTF.setText("Halliday");
        kategoriTF.setText("Pendidikan");
        stokTF.setText("4");
    }
    }//GEN-LAST:event_cariBTActionPerformed

    private void stokTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokTFActionPerformed

    private void judulbukuTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulbukuTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulbukuTFActionPerformed

    private void idpeminjamanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpeminjamanTFActionPerformed
         idpeminjamanTF.setText(
        idpeminjamanTF.getText().toUpperCase()
    );
    }//GEN-LAST:event_idpeminjamanTFActionPerformed

    private void tglpinjamTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpinjamTFActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    tglpinjamTF.setText(sdf.format(new Date()));
    }//GEN-LAST:event_tglpinjamTFActionPerformed

    private void keteranganTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keteranganTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keteranganTFActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
         int row = peminjamanTB.getSelectedRow();

    if(row >= 0){

        DefaultTableModel model =
                (DefaultTableModel) peminjamanTB.getModel();

        model.setValueAt(idpeminjamanTF.getText(), row, 1);
        model.setValueAt(peminjamCMB.getSelectedItem(), row, 2);
        model.setValueAt(namapeminjamTF.getText(), row, 3);
        model.setValueAt(idbukuCMB.getSelectedItem(), row, 4);
        model.setValueAt(judulbukuTF.getText(), row, 5);
        model.setValueAt(tglpinjamTF.getText(), row, 6);
        model.setValueAt(tglkembaliTF.getText(), row, 7);
    }
    }//GEN-LAST:event_editBTActionPerformed

    private void resetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTActionPerformed
        namapeminjamTF.setText("");
    nomorteleponTF.setText("");
    alamatTF.setText("");

    judulbukuTF.setText("");
    penulisTF.setText("");
    kategoriTF.setText("");
    stokTF.setText("");

    idpeminjamanTF.setText("");
    petugasTF.setText("");
    tglpinjamTF.setText("");
    tglkembaliTF.setText("");
    keteranganTF.setText("");
    }//GEN-LAST:event_resetBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        DefaultTableModel model =
            (DefaultTableModel) peminjamanTB.getModel();

    int row = peminjamanTB.getSelectedRow();

    if (row >= 0) {
        model.removeRow(row);

        totaldataTF.setText(
                String.valueOf(model.getRowCount())
        );
    }
    }//GEN-LAST:event_hapusBTActionPerformed

    private void totaldataTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldataTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaldataTFActionPerformed

    private void petugasTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petugasTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(
                        info.getClassName()
                );
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(
                Peminjaman.class.getName()
        ).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
            new Peminjaman().setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JTextField alamatTF;
    private javax.swing.JButton cariBT;
    private javax.swing.JButton cetakBT;
    private javax.swing.JLabel datapeminajamanLB;
    private javax.swing.JLabel datapeminjamLB;
    private javax.swing.JButton editBT;
    private javax.swing.JButton hapusBT;
    private javax.swing.JComboBox<String> idbukuCMB;
    private javax.swing.JTextField idpeminjamanTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulLB;
    private javax.swing.JTextField judulbukuTF;
    private javax.swing.JTextField kategoriTF;
    private javax.swing.JButton kembaliBT;
    private javax.swing.JTextField keteranganTF;
    private javax.swing.JTextField namapeminjamTF;
    private javax.swing.JTextField nomorteleponTF;
    private javax.swing.JComboBox<String> peminjamCMB;
    private javax.swing.JTable peminjamanTB;
    private javax.swing.JTextField penulisTF;
    private javax.swing.JLabel perpustakaanLB;
    private javax.swing.JTextField petugasTF;
    private javax.swing.JButton resetBT;
    private javax.swing.JButton simpanBT;
    private javax.swing.JTextField stokTF;
    private javax.swing.JTextField tanggalTF;
    private javax.swing.JTextField tglkembaliTF;
    private javax.swing.JTextField tglpinjamTF;
    private javax.swing.JLabel totaldataLB;
    private javax.swing.JTextField totaldataTF;
    // End of variables declaration//GEN-END:variables
}